version: "3"

vars:
  TAILWIND_CMD:
    sh: command -v ./tailwindcss >/dev/null 2>&1 && echo "./tailwindcss" || echo "npx tailwindcss@latest"

tasks:
  fmt:
    desc: Run go format
    cmds:
      - go fmt ./...

  vet:
    deps: [fmt]
    desc: Run go Vet
    cmds:
      - go vet ./...
  
  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - templ generate --watch --proxy="http://localhost:8090" --cmd="go run ./cmd/goove/main.go" --open-browser=false

  tailwind:
    desc: Watch Tailwind CSS changes
    cmds:
      - "{{.TAILWIND_CMD}} -i ./static/css/input.css -o ./static/css/output.css --watch"

  dev:
    desc: Start development server with hot reload
    cmds:
      - task --parallel tailwind templ
